Update workflow

diff --git a/.github/workflows/01-buliding_blocks.yaml b/.github/workflows/01-buliding_blocks.yaml
--- a/.github/workflows/01-buliding_blocks.yaml
+++ b/.github/workflows/01-buliding_blocks.yaml
@@ -9,3 +9,12 @@ jobs:
         steps:
             - name: Echo Hello World
               run: echo "Hello, World!"
+    echo-goodbye:
+        runs-on: ubuntu-latest
+        steps:
+            - name: Failed Step
+              run: |
+                echo "This step will fail"
+                exit 1
+            - name: Echo Goodbye
+              run: echo "Goodbye, World!"
